import Other from "../page/product/oil";
import Meatmf from "../page/product/oil/modify";
import Vegetablemf from "../page/product/oil/modify";
import Vegetable from "../page/product/oil";
import Fruit from "../page/product/fruit";
import Oiladd from "../page/product/oil/add";

export const RouteConfig={
    home:{
        key:'home',
        title:'首页',
        pathname:'/'
    },
    user:{
        key:'user',
        title:'用户管理',
        pathname:'/user'
    },
    category:{
        key:'category',
        title:'订单列表',
        pathname:'/category'
    },
    addCategory:{
        key:'addCategory',
        title:'订单添加',
        pathname:'/categoryadd'
    },
    configList:{
        key:'configList',
        title:'非遗列表',
        pathname:'/config'
    },
    configAdd:{
        key:'configAdd',
        title:'非遗添加',
        pathname:'/configadd'
    },
    configMf:{
        key:'configMf',
        title:'非遗修改',
        pathname:'/configmf'
    },
    categoryMf:{
        key:'categoryMf',
        title:'订单修改',
        pathname:'/categorymf'
    },
    Vendorlist:{
        key:'Vendorlist',
        title:'商贩列表',
        pathname:'/vendor'
    },
    Vendoradd:{
        key:'Vendoradd',
        title:'商贩添加',
        pathname:'/vendoradd'
    },
    Vendormf:{
        key:'Vendormf',
        title:'商贩信息修改',
        pathname:'/vendormf'
    },
    Recommend:{
        key:'Recommend',
        title:'精选',
        pathname:'/recommead'
    },
    Recommendadd:{
        key:'Recommendadd',
        title:'精选添加',
        pathname:'/recommeadadd'
    },
    Recommendmd:{
        key:'Recommendmd',
        title:'精选修改',
        pathname:'/recommeadmf'
    },
    Oil:{
        key:'Oil',
        title:'粮油',
        pathname:'/oil'
    },
    Oiladd:{
        key:'Oiladd',
        title:'粮油添加',
        pathname:'/oiladd'
    },
    Oilmf:{
        key:'Oilmf',
        title:'粮油修改',
        pathname:'/oilmf'
    },
    Fruit:{
        key:'Fruit',
        title:'水果',
        pathname:'/fruit'
    },
    Fruitadd:{
        key:'Fruitadd',
        title:'水果添加',
        pathname:'/fruitadd'
    },
    Fruitmf:{
        key:'Fruitmf',
        title:'水果修改',
        pathname:'/fruitmf'
    },
    Vegetable:{
        key:'Vegetable',
        title:'蔬菜',
        pathname:'/vegetable'
    },
    Vegetableadd:{
        key:'Vegetableadd',
        title:'蔬菜添加',
        pathname:'/vegetableadd'
    },
    Vegetablemf:{
        key:'Vegetablemf',
        title:'蔬菜修改',
        pathname:'/vegetablemf'
    },
    Meat:{
        key:'Meat',
        title:'肉禽',
        pathname:'/meat'
    },
    Meatadd:{
        key:'Meatadd',
        title:'肉禽添加',
        pathname:'/meatadd'
    },
    Meatmf:{
        key:'Meatmf',
        title:'肉禽修改',
        pathname:'/meatmf'
    },
    Other:{
        key:'Other',
        title:'其他',
        pathname:'/other'
    },
    Otheradd:{
        key:'Otheradd',
        title:'其他添加',
        pathname:'/otheradd'
    },
    Othermf:{
        key:'Othermf',
        title:'其他修改',
        pathname:'/othermf'
    },
    Chart:{
        key:'Chart',
        title:'数据分析',
        pathname:'/charts'
    },
    Employ:{
        key:'Employ',
        title:'招聘推荐列表',
        pathname:'/employ'
    },
    Employadd:{
        key:'Employadd',
        title:'添加招聘',
        pathname:'/employadd'
    },
    Employmf:{
        key:'Employmf',
        title:'修改招聘',
        pathname:'/employmf'
    },
    LocalKid:{
        key:'LocalKid',
        title:'信息列表',
        pathname:'/localkid'
    },
    LocalKidadd:{
        key:'LocalKidadd',
        title:'添加信息',
        pathname:'/localkidadd'
    },
    LocalKidmf:{
        key:'LocalKidmf',
        title:'修改信息',
        pathname:'/localkidmf'
    },
    LocalOld:{
        key:'LocalOld',
        title:'信息列表',
        pathname:'/localold'
    },
    LocalOldadd:{
        key:'LocalOldadd',
        title:'添加信息',
        pathname:'/localoldadd'
    },
    LocalOldmf:{
        key:'LocalOldmf',
        title:'修改信息',
        pathname:'/localoldmf'
    },
    LocalTeen:{
        key:'LocalTeen',
        title:'信息列表',
        pathname:'/localteen'
    },
    LocalTeenadd:{
        key:'LocalTeenadd',
        title:'添加信息',
        pathname:'/localteenadd'
    },
    LocalTeenmf:{
        key:'LocalTeenmf',
        title:'修改信息',
        pathname:'/localteenmf'
    },
    Videolist:{
        key:'Videolist',
        title:'视频列表',
        pathname:'/videolist'
    },
    Videoadd:{
        key:'Videoadd',
        title:'添加视频',
        pathname:'/videoadd'
    },
    Videomf:{
        key:'Videomf',
        title:'删除视频',
        pathname:'/videomf'
    },
    ShopList:{
        key:'ShopList',
        title:'店铺列表',
        pathname:'/shoplist'
    },
    Shopadd:{
        key:'Shopadd',
        title:'添加店铺',
        pathname:'/shopadd'
    },
    Shopmf:{
        key:'Shopmf',
        title:'店铺修改',
        pathname:'/shopmf'
    }


};

export default class NavigationUtil{
    static goto(route,history){
        const {pathname} = route;
        if(!history || !pathname) {
            console.log('history && pathname cannot be null.')
        }
        return params=>{
            history.push({
                pathname,
                ...(params || {})
            })
        }
    }
}
